[package]
name = "assur_ui"
version = "0.1.0"
edition = "2021"
links = "libwx_backend"
build="build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[build-dependencies]
cmake = "0.1.49"